/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTestAiRouteImport } from './routes/api/test-ai'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAuditsIndexRouteImport } from './routes/_authenticated/audits.index'
import { Route as ApiPublicTestAiRouteImport } from './routes/api/public/test-ai'
import { Route as AuthenticatedAuditsNewRouteImport } from './routes/_authenticated/audits.new'
import { Route as AuthenticatedAuditsIdRouteImport } from './routes/_authenticated/audits.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestAiRoute = ApiTestAiRouteImport.update({
  id: '/api/test-ai',
  path: '/api/test-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsIndexRoute =
  AuthenticatedAuditsIndexRouteImport.update({
    id: '/audits/',
    path: '/audits/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTestAiRoute = ApiPublicTestAiRouteImport.update({
  id: '/api/public/test-ai',
  path: '/api/public/test-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditsNewRoute = AuthenticatedAuditsNewRouteImport.update({
  id: '/audits/new',
  path: '/audits/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditsIdRoute = AuthenticatedAuditsIdRouteImport.update({
  id: '/audits/$id',
  path: '/audits/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/test-ai': typeof ApiTestAiRoute
  '/audits/$id': typeof AuthenticatedAuditsIdRoute
  '/audits/new': typeof AuthenticatedAuditsNewRoute
  '/api/public/test-ai': typeof ApiPublicTestAiRoute
  '/audits/': typeof AuthenticatedAuditsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/test-ai': typeof ApiTestAiRoute
  '/audits/$id': typeof AuthenticatedAuditsIdRoute
  '/audits/new': typeof AuthenticatedAuditsNewRoute
  '/api/public/test-ai': typeof ApiPublicTestAiRoute
  '/audits': typeof AuthenticatedAuditsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/test-ai': typeof ApiTestAiRoute
  '/_authenticated/audits/$id': typeof AuthenticatedAuditsIdRoute
  '/_authenticated/audits/new': typeof AuthenticatedAuditsNewRoute
  '/api/public/test-ai': typeof ApiPublicTestAiRoute
  '/_authenticated/audits/': typeof AuthenticatedAuditsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/test-ai'
    | '/audits/$id'
    | '/audits/new'
    | '/api/public/test-ai'
    | '/audits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/test-ai'
    | '/audits/$id'
    | '/audits/new'
    | '/api/public/test-ai'
    | '/audits'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/api/test-ai'
    | '/_authenticated/audits/$id'
    | '/_authenticated/audits/new'
    | '/api/public/test-ai'
    | '/_authenticated/audits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiTestAiRoute: typeof ApiTestAiRoute
  ApiPublicTestAiRoute: typeof ApiPublicTestAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-ai': {
      id: '/api/test-ai'
      path: '/api/test-ai'
      fullPath: '/api/test-ai'
      preLoaderRoute: typeof ApiTestAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/': {
      id: '/_authenticated/audits/'
      path: '/audits'
      fullPath: '/audits/'
      preLoaderRoute: typeof AuthenticatedAuditsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/test-ai': {
      id: '/api/public/test-ai'
      path: '/api/public/test-ai'
      fullPath: '/api/public/test-ai'
      preLoaderRoute: typeof ApiPublicTestAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audits/new': {
      id: '/_authenticated/audits/new'
      path: '/audits/new'
      fullPath: '/audits/new'
      preLoaderRoute: typeof AuthenticatedAuditsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audits/$id': {
      id: '/_authenticated/audits/$id'
      path: '/audits/$id'
      fullPath: '/audits/$id'
      preLoaderRoute: typeof AuthenticatedAuditsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAuditsIdRoute: typeof AuthenticatedAuditsIdRoute
  AuthenticatedAuditsNewRoute: typeof AuthenticatedAuditsNewRoute
  AuthenticatedAuditsIndexRoute: typeof AuthenticatedAuditsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAuditsIdRoute: AuthenticatedAuditsIdRoute,
  AuthenticatedAuditsNewRoute: AuthenticatedAuditsNewRoute,
  AuthenticatedAuditsIndexRoute: AuthenticatedAuditsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiTestAiRoute: ApiTestAiRoute,
  ApiPublicTestAiRoute: ApiPublicTestAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
